runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images
env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/gc-blog-193800:us-central1:gc-blog-sql;dbname=blog_db
  MYSQL_USER: root
  MYSQL_PASSWORD: gcblog123
